// Auto-generated by glu codegen. Do not edit.

pub const Twist = struct {
    seq: u32,
    timestamp: i64,
    linear_x: f32,
    linear_y: f32,
    angular_z: f32,
};

pub const Odometry = struct {
    seq: u32,
    timestamp: i64,
    x: f32,
    y: f32,
    theta: f32,
    linear_vel: f32,
    angular_vel: f32,
};

pub const BatteryStatus = struct {
    seq: u32,
    timestamp: i64,
    voltage: f32,
    current: f32,
    percentage: f32,
};
