const std = @import("std");
const parser = @import("parser.zig");
const Msg = parser.Msg;
const Field = parser.Field;

pub fn generate(writer: anytype, msgs: []const Msg) !void {
    try writer.writeAll("// Auto-generated by glu codegen. Do not edit.\n\n");
    for (msgs) |msg| {
        try writer.print("pub const {s} = struct {{\n", .{msg.name});
        for (msg.fields) |f| {
            try writer.print("    {s}: {s},\n", .{ f.name, f.type_ });
        }
        try writer.writeAll("};\n\n");
    }
}

test "generate struct definitions" {
    const fields = [_]Field{
        .{ .name = "x", .type_ = "f64" },
        .{ .name = "y", .type_ = "f64" },
    };
    const msgs = [_]Msg{
        .{ .name = "Vec2", .fields = &fields },
    };

    var aw = std.Io.Writer.Allocating.init(std.testing.allocator);
    defer aw.deinit();

    try generate(&aw.writer, &msgs);

    const expected =
        "// Auto-generated by glu codegen. Do not edit.\n\n" ++
        \\pub const Vec2 = struct {
        \\    x: f64,
        \\    y: f64,
        \\};
        \\
        \\
        ;
    try std.testing.expectEqualStrings(expected, aw.written());
}
