const std = @import("std");
const parser = @import("parser.zig");
const Msg = parser.Msg;
const Field = parser.Field;

pub fn generate(allocator: std.mem.Allocator, init: std.process.Init, msgs: []const Msg, out_path: []const u8) !void {
    const cwd = std.Io.Dir.cwd();

    if (std.fs.path.dirname(out_path)) |dir| {
        try cwd.createDirPath(init.io, dir);
    }

    const file = try cwd.createFile(init.io, out_path, .{});
    defer file.close(init.io);

    const header: []const u8 = "// Auto-generated by glu codegen. Do not edit.\n\n";
    var offset: u64 = 0;

    try file.writePositionalAll(init.io, header, offset);

    offset += header.len;

    for (msgs) |msg| {
        const def = try std.fmt.allocPrint(allocator, "pub const {s} = struct {{\n", .{msg.name});
        defer allocator.free(def);

        try file.writePositionalAll(init.io, def, offset);

        offset += def.len;

        for (msg.fields) |field| {
            const f = try std.fmt.allocPrint(allocator, "    {s}: {s},\n", .{ field.name, field.type_ });
            defer allocator.free(f);

            try file.writePositionalAll(init.io, f, offset);

            offset += f.len;
        }

        const closing: []const u8 = "};\n";
        try file.writePositionalAll(init.io, closing, offset);
        offset += closing.len;
    }
}

test "generate struct definitions" {
    const fields = [_]Field{
        .{ .name = "x", .type_ = "f64" },
        .{ .name = "y", .type_ = "f64" },
    };
    const msgs = [_]Msg{
        .{ .name = "Vec2", .fields = &fields },
    };

    const allocator = std.testing.allocator;
    const init: std.process.Init = .{
        .minimal = .{
            .environ = std.process.Environ.empty,
            .args = .{ .vector = &.{} },
        },
        .arena = undefined,
        .gpa = allocator,
        .io = std.testing.io,
        .environ_map = undefined,
        .preopens = std.process.Preopens.empty,
    };

    const cwd = std.Io.Dir.cwd();
    cwd.deleteTree(init.io, "gen") catch {};
    try cwd.createDirPath(init.io, "gen");

    try generate(allocator, init, &msgs, "gen/msgs.zig");

    var file = try cwd.openFile(init.io, "gen/msgs.zig", .{});
    defer file.close(init.io);

    const size = @as(usize, @intCast(try file.length(init.io)));
    const content = try allocator.alloc(u8, size);
    defer allocator.free(content);
    _ = try file.readPositionalAll(init.io, content, 0);

    const expected =
        "// Auto-generated by glu codegen. Do not edit.\n\n" ++
        "pub const Vec2 = struct {\n" ++
        "    x: f64,\n" ++
        "    y: f64,\n" ++
        "};\n";

    try std.testing.expectEqualSlices(u8, expected, content);

    _ = cwd.deleteTree(init.io, "gen") catch {};
}
