// Auto-generated by glu codegen. Do not edit.

pub const RawSensor = struct {
    seq: u32,
    timestamp: i64,
    raw_x: f32,
    raw_y: f32,
    raw_z: f32,
    noise: f32,
};

pub const Filtered = struct {
    seq: u32,
    timestamp: i64,
    x: f32,
    y: f32,
    z: f32,
    magnitude: f32,
};

pub const MotorCmd = struct {
    seq: u32,
    timestamp: i64,
    left_pwm: f32,
    right_pwm: f32,
    enabled: u8,
};
